<?php
/**
 * Form1099MiscListItem
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Avalara\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/*
 * AvaTax Software Development Kit for PHP
 *
 * (c) 2004-2025 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Avalara 1099 & W-9 API Definition
 *
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * @category   Avalara client libraries
 * @package    Avalara\SDK\API\A1099\V2
 * @author     Sachin Baijal <sachin.baijal@avalara.com>
 * @author     Jonathan Wenger <jonathan.wenger@avalara.com>
 * @copyright  2004-2025 Avalara, Inc.
 * @license    https://www.apache.org/licenses/LICENSE-2.0
 * @link       https://github.com/avadev/AvaTax-REST-V3-PHP-SDK

 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Avalara\SDK\Model\A1099\V2;

use \ArrayAccess;
use \Avalara\SDK\ObjectSerializer;
use \Avalara\SDK\Model\ModelInterface;
/**
 * Form1099MiscListItem Class Doc Comment
 *
 * @category Class
 * @package  Avalara\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Form1099MiscListItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Form1099MiscListItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'second_tin_notice' => 'bool',
        'rents' => 'float',
        'royalties' => 'float',
        'other_income' => 'float',
        'fed_income_tax_withheld' => 'float',
        'fishing_boat_proceeds' => 'float',
        'medical_health_care_payments' => 'float',
        'direct_sales_indicator' => 'bool',
        'substitute_payments' => 'float',
        'crop_insurance_proceeds' => 'float',
        'gross_proceeds_paid_to_attorney' => 'float',
        'fish_purchased_for_resale' => 'float',
        'section409_a_deferrals' => 'float',
        'fatca_filing_requirement' => 'bool',
        'excess_golden_parachute_payments' => 'float',
        'nonqualified_deferred_compensation' => 'float',
        'issuer_reference_id' => 'string',
        'issuer_tin' => 'string',
        'tax_year' => 'int',
        'issuer_id' => 'string',
        'reference_id' => 'string',
        'recipient_tin' => 'string',
        'recipient_name' => 'string',
        'tin_type' => 'string',
        'recipient_second_name' => 'string',
        'address' => 'string',
        'address2' => 'string',
        'city' => 'string',
        'state' => 'string',
        'zip' => 'string',
        'recipient_email' => 'string',
        'account_number' => 'string',
        'office_code' => 'string',
        'recipient_non_us_province' => 'string',
        'country_code' => 'string',
        'federal_e_file' => 'bool',
        'postal_mail' => 'bool',
        'state_e_file' => 'bool',
        'tin_match' => 'bool',
        'address_verification' => 'bool',
        'state_and_local_withholding' => '\Avalara\SDK\Model\A1099\V2\StateAndLocalWithholdingRequest'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'second_tin_notice' => null,
        'rents' => 'double',
        'royalties' => 'double',
        'other_income' => 'double',
        'fed_income_tax_withheld' => 'double',
        'fishing_boat_proceeds' => 'double',
        'medical_health_care_payments' => 'double',
        'direct_sales_indicator' => null,
        'substitute_payments' => 'double',
        'crop_insurance_proceeds' => 'double',
        'gross_proceeds_paid_to_attorney' => 'double',
        'fish_purchased_for_resale' => 'double',
        'section409_a_deferrals' => 'double',
        'fatca_filing_requirement' => null,
        'excess_golden_parachute_payments' => 'double',
        'nonqualified_deferred_compensation' => 'double',
        'issuer_reference_id' => null,
        'issuer_tin' => null,
        'tax_year' => 'int32',
        'issuer_id' => null,
        'reference_id' => null,
        'recipient_tin' => null,
        'recipient_name' => null,
        'tin_type' => null,
        'recipient_second_name' => null,
        'address' => null,
        'address2' => null,
        'city' => null,
        'state' => null,
        'zip' => null,
        'recipient_email' => null,
        'account_number' => null,
        'office_code' => null,
        'recipient_non_us_province' => null,
        'country_code' => null,
        'federal_e_file' => null,
        'postal_mail' => null,
        'state_e_file' => null,
        'tin_match' => null,
        'address_verification' => null,
        'state_and_local_withholding' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'second_tin_notice' => 'secondTinNotice',
        'rents' => 'rents',
        'royalties' => 'royalties',
        'other_income' => 'otherIncome',
        'fed_income_tax_withheld' => 'fedIncomeTaxWithheld',
        'fishing_boat_proceeds' => 'fishingBoatProceeds',
        'medical_health_care_payments' => 'medicalHealthCarePayments',
        'direct_sales_indicator' => 'directSalesIndicator',
        'substitute_payments' => 'substitutePayments',
        'crop_insurance_proceeds' => 'cropInsuranceProceeds',
        'gross_proceeds_paid_to_attorney' => 'grossProceedsPaidToAttorney',
        'fish_purchased_for_resale' => 'fishPurchasedForResale',
        'section409_a_deferrals' => 'section409ADeferrals',
        'fatca_filing_requirement' => 'fatcaFilingRequirement',
        'excess_golden_parachute_payments' => 'excessGoldenParachutePayments',
        'nonqualified_deferred_compensation' => 'nonqualifiedDeferredCompensation',
        'issuer_reference_id' => 'issuerReferenceId',
        'issuer_tin' => 'issuerTin',
        'tax_year' => 'taxYear',
        'issuer_id' => 'issuerId',
        'reference_id' => 'referenceId',
        'recipient_tin' => 'recipientTin',
        'recipient_name' => 'recipientName',
        'tin_type' => 'tinType',
        'recipient_second_name' => 'recipientSecondName',
        'address' => 'address',
        'address2' => 'address2',
        'city' => 'city',
        'state' => 'state',
        'zip' => 'zip',
        'recipient_email' => 'recipientEmail',
        'account_number' => 'accountNumber',
        'office_code' => 'officeCode',
        'recipient_non_us_province' => 'recipientNonUsProvince',
        'country_code' => 'countryCode',
        'federal_e_file' => 'federalEFile',
        'postal_mail' => 'postalMail',
        'state_e_file' => 'stateEFile',
        'tin_match' => 'tinMatch',
        'address_verification' => 'addressVerification',
        'state_and_local_withholding' => 'stateAndLocalWithholding'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'second_tin_notice' => 'setSecondTinNotice',
        'rents' => 'setRents',
        'royalties' => 'setRoyalties',
        'other_income' => 'setOtherIncome',
        'fed_income_tax_withheld' => 'setFedIncomeTaxWithheld',
        'fishing_boat_proceeds' => 'setFishingBoatProceeds',
        'medical_health_care_payments' => 'setMedicalHealthCarePayments',
        'direct_sales_indicator' => 'setDirectSalesIndicator',
        'substitute_payments' => 'setSubstitutePayments',
        'crop_insurance_proceeds' => 'setCropInsuranceProceeds',
        'gross_proceeds_paid_to_attorney' => 'setGrossProceedsPaidToAttorney',
        'fish_purchased_for_resale' => 'setFishPurchasedForResale',
        'section409_a_deferrals' => 'setSection409ADeferrals',
        'fatca_filing_requirement' => 'setFatcaFilingRequirement',
        'excess_golden_parachute_payments' => 'setExcessGoldenParachutePayments',
        'nonqualified_deferred_compensation' => 'setNonqualifiedDeferredCompensation',
        'issuer_reference_id' => 'setIssuerReferenceId',
        'issuer_tin' => 'setIssuerTin',
        'tax_year' => 'setTaxYear',
        'issuer_id' => 'setIssuerId',
        'reference_id' => 'setReferenceId',
        'recipient_tin' => 'setRecipientTin',
        'recipient_name' => 'setRecipientName',
        'tin_type' => 'setTinType',
        'recipient_second_name' => 'setRecipientSecondName',
        'address' => 'setAddress',
        'address2' => 'setAddress2',
        'city' => 'setCity',
        'state' => 'setState',
        'zip' => 'setZip',
        'recipient_email' => 'setRecipientEmail',
        'account_number' => 'setAccountNumber',
        'office_code' => 'setOfficeCode',
        'recipient_non_us_province' => 'setRecipientNonUsProvince',
        'country_code' => 'setCountryCode',
        'federal_e_file' => 'setFederalEFile',
        'postal_mail' => 'setPostalMail',
        'state_e_file' => 'setStateEFile',
        'tin_match' => 'setTinMatch',
        'address_verification' => 'setAddressVerification',
        'state_and_local_withholding' => 'setStateAndLocalWithholding'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'second_tin_notice' => 'getSecondTinNotice',
        'rents' => 'getRents',
        'royalties' => 'getRoyalties',
        'other_income' => 'getOtherIncome',
        'fed_income_tax_withheld' => 'getFedIncomeTaxWithheld',
        'fishing_boat_proceeds' => 'getFishingBoatProceeds',
        'medical_health_care_payments' => 'getMedicalHealthCarePayments',
        'direct_sales_indicator' => 'getDirectSalesIndicator',
        'substitute_payments' => 'getSubstitutePayments',
        'crop_insurance_proceeds' => 'getCropInsuranceProceeds',
        'gross_proceeds_paid_to_attorney' => 'getGrossProceedsPaidToAttorney',
        'fish_purchased_for_resale' => 'getFishPurchasedForResale',
        'section409_a_deferrals' => 'getSection409ADeferrals',
        'fatca_filing_requirement' => 'getFatcaFilingRequirement',
        'excess_golden_parachute_payments' => 'getExcessGoldenParachutePayments',
        'nonqualified_deferred_compensation' => 'getNonqualifiedDeferredCompensation',
        'issuer_reference_id' => 'getIssuerReferenceId',
        'issuer_tin' => 'getIssuerTin',
        'tax_year' => 'getTaxYear',
        'issuer_id' => 'getIssuerId',
        'reference_id' => 'getReferenceId',
        'recipient_tin' => 'getRecipientTin',
        'recipient_name' => 'getRecipientName',
        'tin_type' => 'getTinType',
        'recipient_second_name' => 'getRecipientSecondName',
        'address' => 'getAddress',
        'address2' => 'getAddress2',
        'city' => 'getCity',
        'state' => 'getState',
        'zip' => 'getZip',
        'recipient_email' => 'getRecipientEmail',
        'account_number' => 'getAccountNumber',
        'office_code' => 'getOfficeCode',
        'recipient_non_us_province' => 'getRecipientNonUsProvince',
        'country_code' => 'getCountryCode',
        'federal_e_file' => 'getFederalEFile',
        'postal_mail' => 'getPostalMail',
        'state_e_file' => 'getStateEFile',
        'tin_match' => 'getTinMatch',
        'address_verification' => 'getAddressVerification',
        'state_and_local_withholding' => 'getStateAndLocalWithholding'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const TIN_TYPE_EIN = 'EIN';
    const TIN_TYPE_SSN = 'SSN';
    const TIN_TYPE_ITIN = 'ITIN';
    const TIN_TYPE_ATIN = 'ATIN';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTinTypeAllowableValues()
    {
        return [
            self::TIN_TYPE_EIN,
            self::TIN_TYPE_SSN,
            self::TIN_TYPE_ITIN,
            self::TIN_TYPE_ATIN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['second_tin_notice'] = $data['second_tin_notice'] ?? null;
        $this->container['rents'] = $data['rents'] ?? null;
        $this->container['royalties'] = $data['royalties'] ?? null;
        $this->container['other_income'] = $data['other_income'] ?? null;
        $this->container['fed_income_tax_withheld'] = $data['fed_income_tax_withheld'] ?? null;
        $this->container['fishing_boat_proceeds'] = $data['fishing_boat_proceeds'] ?? null;
        $this->container['medical_health_care_payments'] = $data['medical_health_care_payments'] ?? null;
        $this->container['direct_sales_indicator'] = $data['direct_sales_indicator'] ?? null;
        $this->container['substitute_payments'] = $data['substitute_payments'] ?? null;
        $this->container['crop_insurance_proceeds'] = $data['crop_insurance_proceeds'] ?? null;
        $this->container['gross_proceeds_paid_to_attorney'] = $data['gross_proceeds_paid_to_attorney'] ?? null;
        $this->container['fish_purchased_for_resale'] = $data['fish_purchased_for_resale'] ?? null;
        $this->container['section409_a_deferrals'] = $data['section409_a_deferrals'] ?? null;
        $this->container['fatca_filing_requirement'] = $data['fatca_filing_requirement'] ?? null;
        $this->container['excess_golden_parachute_payments'] = $data['excess_golden_parachute_payments'] ?? null;
        $this->container['nonqualified_deferred_compensation'] = $data['nonqualified_deferred_compensation'] ?? null;
        $this->container['issuer_reference_id'] = $data['issuer_reference_id'] ?? null;
        $this->container['issuer_tin'] = $data['issuer_tin'] ?? null;
        $this->container['tax_year'] = $data['tax_year'] ?? null;
        $this->container['issuer_id'] = $data['issuer_id'] ?? null;
        $this->container['reference_id'] = $data['reference_id'] ?? null;
        $this->container['recipient_tin'] = $data['recipient_tin'] ?? null;
        $this->container['recipient_name'] = $data['recipient_name'] ?? null;
        $this->container['tin_type'] = $data['tin_type'] ?? null;
        $this->container['recipient_second_name'] = $data['recipient_second_name'] ?? null;
        $this->container['address'] = $data['address'] ?? null;
        $this->container['address2'] = $data['address2'] ?? null;
        $this->container['city'] = $data['city'] ?? null;
        $this->container['state'] = $data['state'] ?? null;
        $this->container['zip'] = $data['zip'] ?? null;
        $this->container['recipient_email'] = $data['recipient_email'] ?? null;
        $this->container['account_number'] = $data['account_number'] ?? null;
        $this->container['office_code'] = $data['office_code'] ?? null;
        $this->container['recipient_non_us_province'] = $data['recipient_non_us_province'] ?? null;
        $this->container['country_code'] = $data['country_code'] ?? null;
        $this->container['federal_e_file'] = $data['federal_e_file'] ?? null;
        $this->container['postal_mail'] = $data['postal_mail'] ?? null;
        $this->container['state_e_file'] = $data['state_e_file'] ?? null;
        $this->container['tin_match'] = $data['tin_match'] ?? null;
        $this->container['address_verification'] = $data['address_verification'] ?? null;
        $this->container['state_and_local_withholding'] = $data['state_and_local_withholding'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tax_year'] === null) {
            $invalidProperties[] = "'tax_year' can't be null";
        }
        if ($this->container['recipient_name'] === null) {
            $invalidProperties[] = "'recipient_name' can't be null";
        }
        if ((mb_strlen($this->container['recipient_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'recipient_name', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getTinTypeAllowableValues();
        if (!is_null($this->container['tin_type']) && !in_array($this->container['tin_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tin_type', must be one of '%s'",
                $this->container['tin_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['address'] === null) {
            $invalidProperties[] = "'address' can't be null";
        }
        if ((mb_strlen($this->container['address']) < 1)) {
            $invalidProperties[] = "invalid value for 'address', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['city'] === null) {
            $invalidProperties[] = "'city' can't be null";
        }
        if ((mb_strlen($this->container['city']) < 1)) {
            $invalidProperties[] = "invalid value for 'city', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['country_code'] === null) {
            $invalidProperties[] = "'country_code' can't be null";
        }
        if ((mb_strlen($this->container['country_code']) < 1)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets second_tin_notice
     *
     * @return bool|null
     */
    public function getSecondTinNotice()
    {
        return $this->container['second_tin_notice'];
    }

    /**
     * Sets second_tin_notice
     *
     * @param bool|null $second_tin_notice Second TIN notice
     *
     * @return self
     */
    public function setSecondTinNotice($second_tin_notice)
    {
        $this->container['second_tin_notice'] = $second_tin_notice;

        return $this;
    }

    /**
     * Gets rents
     *
     * @return float|null
     */
    public function getRents()
    {
        return $this->container['rents'];
    }

    /**
     * Sets rents
     *
     * @param float|null $rents Rents
     *
     * @return self
     */
    public function setRents($rents)
    {
        $this->container['rents'] = $rents;

        return $this;
    }

    /**
     * Gets royalties
     *
     * @return float|null
     */
    public function getRoyalties()
    {
        return $this->container['royalties'];
    }

    /**
     * Sets royalties
     *
     * @param float|null $royalties Royalties
     *
     * @return self
     */
    public function setRoyalties($royalties)
    {
        $this->container['royalties'] = $royalties;

        return $this;
    }

    /**
     * Gets other_income
     *
     * @return float|null
     */
    public function getOtherIncome()
    {
        return $this->container['other_income'];
    }

    /**
     * Sets other_income
     *
     * @param float|null $other_income Other income
     *
     * @return self
     */
    public function setOtherIncome($other_income)
    {
        $this->container['other_income'] = $other_income;

        return $this;
    }

    /**
     * Gets fed_income_tax_withheld
     *
     * @return float|null
     */
    public function getFedIncomeTaxWithheld()
    {
        return $this->container['fed_income_tax_withheld'];
    }

    /**
     * Sets fed_income_tax_withheld
     *
     * @param float|null $fed_income_tax_withheld Federal income tax withheld
     *
     * @return self
     */
    public function setFedIncomeTaxWithheld($fed_income_tax_withheld)
    {
        $this->container['fed_income_tax_withheld'] = $fed_income_tax_withheld;

        return $this;
    }

    /**
     * Gets fishing_boat_proceeds
     *
     * @return float|null
     */
    public function getFishingBoatProceeds()
    {
        return $this->container['fishing_boat_proceeds'];
    }

    /**
     * Sets fishing_boat_proceeds
     *
     * @param float|null $fishing_boat_proceeds Fishing boat proceeds
     *
     * @return self
     */
    public function setFishingBoatProceeds($fishing_boat_proceeds)
    {
        $this->container['fishing_boat_proceeds'] = $fishing_boat_proceeds;

        return $this;
    }

    /**
     * Gets medical_health_care_payments
     *
     * @return float|null
     */
    public function getMedicalHealthCarePayments()
    {
        return $this->container['medical_health_care_payments'];
    }

    /**
     * Sets medical_health_care_payments
     *
     * @param float|null $medical_health_care_payments Medical and health care payments
     *
     * @return self
     */
    public function setMedicalHealthCarePayments($medical_health_care_payments)
    {
        $this->container['medical_health_care_payments'] = $medical_health_care_payments;

        return $this;
    }

    /**
     * Gets direct_sales_indicator
     *
     * @return bool|null
     */
    public function getDirectSalesIndicator()
    {
        return $this->container['direct_sales_indicator'];
    }

    /**
     * Sets direct_sales_indicator
     *
     * @param bool|null $direct_sales_indicator Payer made direct sales totaling $5,000 or more of consumer products to recipient for resale
     *
     * @return self
     */
    public function setDirectSalesIndicator($direct_sales_indicator)
    {
        $this->container['direct_sales_indicator'] = $direct_sales_indicator;

        return $this;
    }

    /**
     * Gets substitute_payments
     *
     * @return float|null
     */
    public function getSubstitutePayments()
    {
        return $this->container['substitute_payments'];
    }

    /**
     * Sets substitute_payments
     *
     * @param float|null $substitute_payments Substitute payments in lieu of dividends or interest
     *
     * @return self
     */
    public function setSubstitutePayments($substitute_payments)
    {
        $this->container['substitute_payments'] = $substitute_payments;

        return $this;
    }

    /**
     * Gets crop_insurance_proceeds
     *
     * @return float|null
     */
    public function getCropInsuranceProceeds()
    {
        return $this->container['crop_insurance_proceeds'];
    }

    /**
     * Sets crop_insurance_proceeds
     *
     * @param float|null $crop_insurance_proceeds Crop insurance proceeds
     *
     * @return self
     */
    public function setCropInsuranceProceeds($crop_insurance_proceeds)
    {
        $this->container['crop_insurance_proceeds'] = $crop_insurance_proceeds;

        return $this;
    }

    /**
     * Gets gross_proceeds_paid_to_attorney
     *
     * @return float|null
     */
    public function getGrossProceedsPaidToAttorney()
    {
        return $this->container['gross_proceeds_paid_to_attorney'];
    }

    /**
     * Sets gross_proceeds_paid_to_attorney
     *
     * @param float|null $gross_proceeds_paid_to_attorney Gross proceeds paid to an attorney
     *
     * @return self
     */
    public function setGrossProceedsPaidToAttorney($gross_proceeds_paid_to_attorney)
    {
        $this->container['gross_proceeds_paid_to_attorney'] = $gross_proceeds_paid_to_attorney;

        return $this;
    }

    /**
     * Gets fish_purchased_for_resale
     *
     * @return float|null
     */
    public function getFishPurchasedForResale()
    {
        return $this->container['fish_purchased_for_resale'];
    }

    /**
     * Sets fish_purchased_for_resale
     *
     * @param float|null $fish_purchased_for_resale Fish purchased for resale
     *
     * @return self
     */
    public function setFishPurchasedForResale($fish_purchased_for_resale)
    {
        $this->container['fish_purchased_for_resale'] = $fish_purchased_for_resale;

        return $this;
    }

    /**
     * Gets section409_a_deferrals
     *
     * @return float|null
     */
    public function getSection409ADeferrals()
    {
        return $this->container['section409_a_deferrals'];
    }

    /**
     * Sets section409_a_deferrals
     *
     * @param float|null $section409_a_deferrals Section 409A deferrals
     *
     * @return self
     */
    public function setSection409ADeferrals($section409_a_deferrals)
    {
        $this->container['section409_a_deferrals'] = $section409_a_deferrals;

        return $this;
    }

    /**
     * Gets fatca_filing_requirement
     *
     * @return bool|null
     */
    public function getFatcaFilingRequirement()
    {
        return $this->container['fatca_filing_requirement'];
    }

    /**
     * Sets fatca_filing_requirement
     *
     * @param bool|null $fatca_filing_requirement FATCA filing requirement
     *
     * @return self
     */
    public function setFatcaFilingRequirement($fatca_filing_requirement)
    {
        $this->container['fatca_filing_requirement'] = $fatca_filing_requirement;

        return $this;
    }

    /**
     * Gets excess_golden_parachute_payments
     *
     * @return float|null
     */
    public function getExcessGoldenParachutePayments()
    {
        return $this->container['excess_golden_parachute_payments'];
    }

    /**
     * Sets excess_golden_parachute_payments
     *
     * @param float|null $excess_golden_parachute_payments (Legacy field) Excess golden parachute payments
     *
     * @return self
     */
    public function setExcessGoldenParachutePayments($excess_golden_parachute_payments)
    {
        $this->container['excess_golden_parachute_payments'] = $excess_golden_parachute_payments;

        return $this;
    }

    /**
     * Gets nonqualified_deferred_compensation
     *
     * @return float|null
     */
    public function getNonqualifiedDeferredCompensation()
    {
        return $this->container['nonqualified_deferred_compensation'];
    }

    /**
     * Sets nonqualified_deferred_compensation
     *
     * @param float|null $nonqualified_deferred_compensation Nonqualified deferred compensation
     *
     * @return self
     */
    public function setNonqualifiedDeferredCompensation($nonqualified_deferred_compensation)
    {
        $this->container['nonqualified_deferred_compensation'] = $nonqualified_deferred_compensation;

        return $this;
    }

    /**
     * Gets issuer_reference_id
     *
     * @return string|null
     */
    public function getIssuerReferenceId()
    {
        return $this->container['issuer_reference_id'];
    }

    /**
     * Sets issuer_reference_id
     *
     * @param string|null $issuer_reference_id Issuer Reference ID. One of `issuerReferenceId` or `issuerTin` is required.
     *
     * @return self
     */
    public function setIssuerReferenceId($issuer_reference_id)
    {
        $this->container['issuer_reference_id'] = $issuer_reference_id;

        return $this;
    }

    /**
     * Gets issuer_tin
     *
     * @return string|null
     */
    public function getIssuerTin()
    {
        return $this->container['issuer_tin'];
    }

    /**
     * Sets issuer_tin
     *
     * @param string|null $issuer_tin Issuer TIN. One of `issuerReferenceId` or `issuerTin` is required.
     *
     * @return self
     */
    public function setIssuerTin($issuer_tin)
    {
        $this->container['issuer_tin'] = $issuer_tin;

        return $this;
    }

    /**
     * Gets tax_year
     *
     * @return int
     */
    public function getTaxYear()
    {
        return $this->container['tax_year'];
    }

    /**
     * Sets tax_year
     *
     * @param int $tax_year Tax year
     *
     * @return self
     */
    public function setTaxYear($tax_year)
    {
        $this->container['tax_year'] = $tax_year;

        return $this;
    }

    /**
     * Gets issuer_id
     *
     * @return string|null
     */
    public function getIssuerId()
    {
        return $this->container['issuer_id'];
    }

    /**
     * Sets issuer_id
     *
     * @param string|null $issuer_id Issuer ID
     *
     * @return self
     */
    public function setIssuerId($issuer_id)
    {
        $this->container['issuer_id'] = $issuer_id;

        return $this;
    }

    /**
     * Gets reference_id
     *
     * @return string|null
     */
    public function getReferenceId()
    {
        return $this->container['reference_id'];
    }

    /**
     * Sets reference_id
     *
     * @param string|null $reference_id Reference ID
     *
     * @return self
     */
    public function setReferenceId($reference_id)
    {
        $this->container['reference_id'] = $reference_id;

        return $this;
    }

    /**
     * Gets recipient_tin
     *
     * @return string|null
     */
    public function getRecipientTin()
    {
        return $this->container['recipient_tin'];
    }

    /**
     * Sets recipient_tin
     *
     * @param string|null $recipient_tin Recipient Tax ID Number
     *
     * @return self
     */
    public function setRecipientTin($recipient_tin)
    {
        $this->container['recipient_tin'] = $recipient_tin;

        return $this;
    }

    /**
     * Gets recipient_name
     *
     * @return string
     */
    public function getRecipientName()
    {
        return $this->container['recipient_name'];
    }

    /**
     * Sets recipient_name
     *
     * @param string $recipient_name Recipient name
     *
     * @return self
     */
    public function setRecipientName($recipient_name)
    {

        if ((mb_strlen($recipient_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $recipient_name when calling Form1099MiscListItem., must be bigger than or equal to 1.');
        }

        $this->container['recipient_name'] = $recipient_name;

        return $this;
    }

    /**
     * Gets tin_type
     *
     * @return string|null
     */
    public function getTinType()
    {
        return $this->container['tin_type'];
    }

    /**
     * Sets tin_type
     *
     * @param string|null $tin_type Type of TIN (Tax ID Number). Will be one of:  * SSN  * EIN  * ITIN  * ATIN
     *
     * @return self
     */
    public function setTinType($tin_type)
    {
        $allowedValues = $this->getTinTypeAllowableValues();
        if (!is_null($tin_type) && !in_array($tin_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tin_type', must be one of '%s'",
                    $tin_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tin_type'] = $tin_type;

        return $this;
    }

    /**
     * Gets recipient_second_name
     *
     * @return string|null
     */
    public function getRecipientSecondName()
    {
        return $this->container['recipient_second_name'];
    }

    /**
     * Sets recipient_second_name
     *
     * @param string|null $recipient_second_name Recipient second name
     *
     * @return self
     */
    public function setRecipientSecondName($recipient_second_name)
    {
        $this->container['recipient_second_name'] = $recipient_second_name;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string $address Address
     *
     * @return self
     */
    public function setAddress($address)
    {

        if ((mb_strlen($address) < 1)) {
            throw new \InvalidArgumentException('invalid length for $address when calling Form1099MiscListItem., must be bigger than or equal to 1.');
        }

        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets address2
     *
     * @return string|null
     */
    public function getAddress2()
    {
        return $this->container['address2'];
    }

    /**
     * Sets address2
     *
     * @param string|null $address2 Address line 2
     *
     * @return self
     */
    public function setAddress2($address2)
    {
        $this->container['address2'] = $address2;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city City
     *
     * @return self
     */
    public function setCity($city)
    {

        if ((mb_strlen($city) < 1)) {
            throw new \InvalidArgumentException('invalid length for $city when calling Form1099MiscListItem., must be bigger than or equal to 1.');
        }

        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state US state. Required if CountryCode is \"US\".
     *
     * @return self
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets zip
     *
     * @return string|null
     */
    public function getZip()
    {
        return $this->container['zip'];
    }

    /**
     * Sets zip
     *
     * @param string|null $zip Zip/postal code
     *
     * @return self
     */
    public function setZip($zip)
    {
        $this->container['zip'] = $zip;

        return $this;
    }

    /**
     * Gets recipient_email
     *
     * @return string|null
     */
    public function getRecipientEmail()
    {
        return $this->container['recipient_email'];
    }

    /**
     * Sets recipient_email
     *
     * @param string|null $recipient_email Recipient email address
     *
     * @return self
     */
    public function setRecipientEmail($recipient_email)
    {
        $this->container['recipient_email'] = $recipient_email;

        return $this;
    }

    /**
     * Gets account_number
     *
     * @return string|null
     */
    public function getAccountNumber()
    {
        return $this->container['account_number'];
    }

    /**
     * Sets account_number
     *
     * @param string|null $account_number Account number
     *
     * @return self
     */
    public function setAccountNumber($account_number)
    {
        $this->container['account_number'] = $account_number;

        return $this;
    }

    /**
     * Gets office_code
     *
     * @return string|null
     */
    public function getOfficeCode()
    {
        return $this->container['office_code'];
    }

    /**
     * Sets office_code
     *
     * @param string|null $office_code Office code
     *
     * @return self
     */
    public function setOfficeCode($office_code)
    {
        $this->container['office_code'] = $office_code;

        return $this;
    }

    /**
     * Gets recipient_non_us_province
     *
     * @return string|null
     */
    public function getRecipientNonUsProvince()
    {
        return $this->container['recipient_non_us_province'];
    }

    /**
     * Sets recipient_non_us_province
     *
     * @param string|null $recipient_non_us_province Foreign province
     *
     * @return self
     */
    public function setRecipientNonUsProvince($recipient_non_us_province)
    {
        $this->container['recipient_non_us_province'] = $recipient_non_us_province;

        return $this;
    }

    /**
     * Gets country_code
     *
     * @return string
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string $country_code Country code, as defined at https://www.irs.gov/e-file-providers/country-codes
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {

        if ((mb_strlen($country_code) < 1)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling Form1099MiscListItem., must be bigger than or equal to 1.');
        }

        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets federal_e_file
     *
     * @return bool|null
     */
    public function getFederalEFile()
    {
        return $this->container['federal_e_file'];
    }

    /**
     * Sets federal_e_file
     *
     * @param bool|null $federal_e_file Boolean indicating that federal e-filing should be scheduled for this form
     *
     * @return self
     */
    public function setFederalEFile($federal_e_file)
    {
        $this->container['federal_e_file'] = $federal_e_file;

        return $this;
    }

    /**
     * Gets postal_mail
     *
     * @return bool|null
     */
    public function getPostalMail()
    {
        return $this->container['postal_mail'];
    }

    /**
     * Sets postal_mail
     *
     * @param bool|null $postal_mail Boolean indicating that postal mailing to the recipient should be scheduled for this form
     *
     * @return self
     */
    public function setPostalMail($postal_mail)
    {
        $this->container['postal_mail'] = $postal_mail;

        return $this;
    }

    /**
     * Gets state_e_file
     *
     * @return bool|null
     */
    public function getStateEFile()
    {
        return $this->container['state_e_file'];
    }

    /**
     * Sets state_e_file
     *
     * @param bool|null $state_e_file Boolean indicating that state e-filing should be scheduled for this form
     *
     * @return self
     */
    public function setStateEFile($state_e_file)
    {
        $this->container['state_e_file'] = $state_e_file;

        return $this;
    }

    /**
     * Gets tin_match
     *
     * @return bool|null
     */
    public function getTinMatch()
    {
        return $this->container['tin_match'];
    }

    /**
     * Sets tin_match
     *
     * @param bool|null $tin_match Boolean indicating that TIN Matching should be scheduled for this form
     *
     * @return self
     */
    public function setTinMatch($tin_match)
    {
        $this->container['tin_match'] = $tin_match;

        return $this;
    }

    /**
     * Gets address_verification
     *
     * @return bool|null
     */
    public function getAddressVerification()
    {
        return $this->container['address_verification'];
    }

    /**
     * Sets address_verification
     *
     * @param bool|null $address_verification Boolean indicating that address verification should be scheduled for this form
     *
     * @return self
     */
    public function setAddressVerification($address_verification)
    {
        $this->container['address_verification'] = $address_verification;

        return $this;
    }

    /**
     * Gets state_and_local_withholding
     *
     * @return \Avalara\SDK\Model\A1099\V2\StateAndLocalWithholdingRequest|null
     */
    public function getStateAndLocalWithholding()
    {
        return $this->container['state_and_local_withholding'];
    }

    /**
     * Sets state_and_local_withholding
     *
     * @param \Avalara\SDK\Model\A1099\V2\StateAndLocalWithholdingRequest|null $state_and_local_withholding State and local withholding information
     *
     * @return self
     */
    public function setStateAndLocalWithholding($state_and_local_withholding)
    {
        $this->container['state_and_local_withholding'] = $state_and_local_withholding;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset):bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset):mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value):void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset):void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize():mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString():string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue():string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


