<?php
/**
 * Form1042SListItemResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Avalara\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/*
 * AvaTax Software Development Kit for PHP
 *
 * (c) 2004-2025 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Avalara 1099 & W-9 API Definition
 *
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * @category   Avalara client libraries
 * @package    Avalara\SDK\API\A1099\V2
 * @author     Sachin Baijal <sachin.baijal@avalara.com>
 * @author     Jonathan Wenger <jonathan.wenger@avalara.com>
 * @copyright  2004-2025 Avalara, Inc.
 * @license    https://www.apache.org/licenses/LICENSE-2.0
 * @link       https://github.com/avadev/AvaTax-REST-V3-PHP-SDK

 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Avalara\SDK\Model\A1099\V2;

use \ArrayAccess;
use \Avalara\SDK\ObjectSerializer;
use \Avalara\SDK\Model\ModelInterface;
/**
 * Form1042SListItemResponse Class Doc Comment
 *
 * @category Class
 * @package  Avalara\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Form1042SListItemResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Form1042SListItemResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'unique_form_id' => 'string',
        'no_tin' => 'bool',
        'recipient_date_of_birth' => '\DateTime',
        'recipient_giin' => 'string',
        'recipient_foreign_tin' => 'string',
        'lob_code' => 'string',
        'income_code' => 'string',
        'gross_income' => 'float',
        'withholding_indicator' => 'string',
        'tax_country_code' => 'string',
        'exemption_code_chap3' => 'string',
        'exemption_code_chap4' => 'string',
        'tax_rate_chap3' => 'string',
        'withholding_allowance' => 'float',
        'federal_tax_withheld' => 'float',
        'tax_not_deposited_indicator' => 'bool',
        'academic_indicator' => 'bool',
        'tax_withheld_other_agents' => 'float',
        'amount_repaid' => 'float',
        'tax_paid_agent' => 'float',
        'chap3_status_code' => 'string',
        'chap4_status_code' => 'string',
        'primary_withholding_agent' => '\Avalara\SDK\Model\A1099\V2\PrimaryWithholdingAgentResponse',
        'intermediary_or_flow_through' => '\Avalara\SDK\Model\A1099\V2\IntermediaryOrFlowThroughResponse',
        'id' => 'string',
        'type' => 'string',
        'issuer_id' => 'int',
        'issuer_reference_id' => 'string',
        'issuer_tin' => 'string',
        'tax_year' => 'int',
        'federal_efile' => 'bool',
        'federal_efile_status' => '\Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse',
        'state_efile' => 'bool',
        'state_efile_status' => '\Avalara\SDK\Model\A1099\V2\StateEfileStatusDetailResponse[]',
        'postal_mail' => 'bool',
        'postal_mail_status' => '\Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse',
        'tin_match' => 'bool',
        'tin_match_status' => '\Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse',
        'address_verification' => 'bool',
        'address_verification_status' => '\Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse',
        'reference_id' => 'string',
        'email' => 'string',
        'tin_type' => 'string',
        'tin' => 'string',
        'recipient_name' => 'string',
        'recipient_second_name' => 'string',
        'address' => 'string',
        'address2' => 'string',
        'city' => 'string',
        'state' => 'string',
        'zip' => 'string',
        'foreign_province' => 'string',
        'country_code' => 'string',
        'validation_errors' => '\Avalara\SDK\Model\A1099\V2\ValidationErrorResponse[]',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'state_and_local_withholding' => '\Avalara\SDK\Model\A1099\V2\StateAndLocalWithholdingResponse'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'unique_form_id' => null,
        'no_tin' => null,
        'recipient_date_of_birth' => 'date-time',
        'recipient_giin' => null,
        'recipient_foreign_tin' => null,
        'lob_code' => null,
        'income_code' => null,
        'gross_income' => 'double',
        'withholding_indicator' => null,
        'tax_country_code' => null,
        'exemption_code_chap3' => null,
        'exemption_code_chap4' => null,
        'tax_rate_chap3' => null,
        'withholding_allowance' => 'double',
        'federal_tax_withheld' => 'double',
        'tax_not_deposited_indicator' => null,
        'academic_indicator' => null,
        'tax_withheld_other_agents' => 'double',
        'amount_repaid' => 'double',
        'tax_paid_agent' => 'double',
        'chap3_status_code' => null,
        'chap4_status_code' => null,
        'primary_withholding_agent' => null,
        'intermediary_or_flow_through' => null,
        'id' => null,
        'type' => null,
        'issuer_id' => 'int32',
        'issuer_reference_id' => null,
        'issuer_tin' => null,
        'tax_year' => 'int32',
        'federal_efile' => null,
        'federal_efile_status' => null,
        'state_efile' => null,
        'state_efile_status' => null,
        'postal_mail' => null,
        'postal_mail_status' => null,
        'tin_match' => null,
        'tin_match_status' => null,
        'address_verification' => null,
        'address_verification_status' => null,
        'reference_id' => null,
        'email' => null,
        'tin_type' => null,
        'tin' => null,
        'recipient_name' => null,
        'recipient_second_name' => null,
        'address' => null,
        'address2' => null,
        'city' => null,
        'state' => null,
        'zip' => null,
        'foreign_province' => null,
        'country_code' => null,
        'validation_errors' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'state_and_local_withholding' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'unique_form_id' => 'uniqueFormId',
        'no_tin' => 'noTin',
        'recipient_date_of_birth' => 'recipientDateOfBirth',
        'recipient_giin' => 'recipientGiin',
        'recipient_foreign_tin' => 'recipientForeignTin',
        'lob_code' => 'lobCode',
        'income_code' => 'incomeCode',
        'gross_income' => 'grossIncome',
        'withholding_indicator' => 'withholdingIndicator',
        'tax_country_code' => 'taxCountryCode',
        'exemption_code_chap3' => 'exemptionCodeChap3',
        'exemption_code_chap4' => 'exemptionCodeChap4',
        'tax_rate_chap3' => 'taxRateChap3',
        'withholding_allowance' => 'withholdingAllowance',
        'federal_tax_withheld' => 'federalTaxWithheld',
        'tax_not_deposited_indicator' => 'taxNotDepositedIndicator',
        'academic_indicator' => 'academicIndicator',
        'tax_withheld_other_agents' => 'taxWithheldOtherAgents',
        'amount_repaid' => 'amountRepaid',
        'tax_paid_agent' => 'taxPaidAgent',
        'chap3_status_code' => 'chap3StatusCode',
        'chap4_status_code' => 'chap4StatusCode',
        'primary_withholding_agent' => 'primaryWithholdingAgent',
        'intermediary_or_flow_through' => 'intermediaryOrFlowThrough',
        'id' => 'id',
        'type' => 'type',
        'issuer_id' => 'issuerId',
        'issuer_reference_id' => 'issuerReferenceId',
        'issuer_tin' => 'issuerTin',
        'tax_year' => 'taxYear',
        'federal_efile' => 'federalEfile',
        'federal_efile_status' => 'federalEfileStatus',
        'state_efile' => 'stateEfile',
        'state_efile_status' => 'stateEfileStatus',
        'postal_mail' => 'postalMail',
        'postal_mail_status' => 'postalMailStatus',
        'tin_match' => 'tinMatch',
        'tin_match_status' => 'tinMatchStatus',
        'address_verification' => 'addressVerification',
        'address_verification_status' => 'addressVerificationStatus',
        'reference_id' => 'referenceId',
        'email' => 'email',
        'tin_type' => 'tinType',
        'tin' => 'tin',
        'recipient_name' => 'recipientName',
        'recipient_second_name' => 'recipientSecondName',
        'address' => 'address',
        'address2' => 'address2',
        'city' => 'city',
        'state' => 'state',
        'zip' => 'zip',
        'foreign_province' => 'foreignProvince',
        'country_code' => 'countryCode',
        'validation_errors' => 'validationErrors',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'state_and_local_withholding' => 'stateAndLocalWithholding'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'unique_form_id' => 'setUniqueFormId',
        'no_tin' => 'setNoTin',
        'recipient_date_of_birth' => 'setRecipientDateOfBirth',
        'recipient_giin' => 'setRecipientGiin',
        'recipient_foreign_tin' => 'setRecipientForeignTin',
        'lob_code' => 'setLobCode',
        'income_code' => 'setIncomeCode',
        'gross_income' => 'setGrossIncome',
        'withholding_indicator' => 'setWithholdingIndicator',
        'tax_country_code' => 'setTaxCountryCode',
        'exemption_code_chap3' => 'setExemptionCodeChap3',
        'exemption_code_chap4' => 'setExemptionCodeChap4',
        'tax_rate_chap3' => 'setTaxRateChap3',
        'withholding_allowance' => 'setWithholdingAllowance',
        'federal_tax_withheld' => 'setFederalTaxWithheld',
        'tax_not_deposited_indicator' => 'setTaxNotDepositedIndicator',
        'academic_indicator' => 'setAcademicIndicator',
        'tax_withheld_other_agents' => 'setTaxWithheldOtherAgents',
        'amount_repaid' => 'setAmountRepaid',
        'tax_paid_agent' => 'setTaxPaidAgent',
        'chap3_status_code' => 'setChap3StatusCode',
        'chap4_status_code' => 'setChap4StatusCode',
        'primary_withholding_agent' => 'setPrimaryWithholdingAgent',
        'intermediary_or_flow_through' => 'setIntermediaryOrFlowThrough',
        'id' => 'setId',
        'type' => 'setType',
        'issuer_id' => 'setIssuerId',
        'issuer_reference_id' => 'setIssuerReferenceId',
        'issuer_tin' => 'setIssuerTin',
        'tax_year' => 'setTaxYear',
        'federal_efile' => 'setFederalEfile',
        'federal_efile_status' => 'setFederalEfileStatus',
        'state_efile' => 'setStateEfile',
        'state_efile_status' => 'setStateEfileStatus',
        'postal_mail' => 'setPostalMail',
        'postal_mail_status' => 'setPostalMailStatus',
        'tin_match' => 'setTinMatch',
        'tin_match_status' => 'setTinMatchStatus',
        'address_verification' => 'setAddressVerification',
        'address_verification_status' => 'setAddressVerificationStatus',
        'reference_id' => 'setReferenceId',
        'email' => 'setEmail',
        'tin_type' => 'setTinType',
        'tin' => 'setTin',
        'recipient_name' => 'setRecipientName',
        'recipient_second_name' => 'setRecipientSecondName',
        'address' => 'setAddress',
        'address2' => 'setAddress2',
        'city' => 'setCity',
        'state' => 'setState',
        'zip' => 'setZip',
        'foreign_province' => 'setForeignProvince',
        'country_code' => 'setCountryCode',
        'validation_errors' => 'setValidationErrors',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'state_and_local_withholding' => 'setStateAndLocalWithholding'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'unique_form_id' => 'getUniqueFormId',
        'no_tin' => 'getNoTin',
        'recipient_date_of_birth' => 'getRecipientDateOfBirth',
        'recipient_giin' => 'getRecipientGiin',
        'recipient_foreign_tin' => 'getRecipientForeignTin',
        'lob_code' => 'getLobCode',
        'income_code' => 'getIncomeCode',
        'gross_income' => 'getGrossIncome',
        'withholding_indicator' => 'getWithholdingIndicator',
        'tax_country_code' => 'getTaxCountryCode',
        'exemption_code_chap3' => 'getExemptionCodeChap3',
        'exemption_code_chap4' => 'getExemptionCodeChap4',
        'tax_rate_chap3' => 'getTaxRateChap3',
        'withholding_allowance' => 'getWithholdingAllowance',
        'federal_tax_withheld' => 'getFederalTaxWithheld',
        'tax_not_deposited_indicator' => 'getTaxNotDepositedIndicator',
        'academic_indicator' => 'getAcademicIndicator',
        'tax_withheld_other_agents' => 'getTaxWithheldOtherAgents',
        'amount_repaid' => 'getAmountRepaid',
        'tax_paid_agent' => 'getTaxPaidAgent',
        'chap3_status_code' => 'getChap3StatusCode',
        'chap4_status_code' => 'getChap4StatusCode',
        'primary_withholding_agent' => 'getPrimaryWithholdingAgent',
        'intermediary_or_flow_through' => 'getIntermediaryOrFlowThrough',
        'id' => 'getId',
        'type' => 'getType',
        'issuer_id' => 'getIssuerId',
        'issuer_reference_id' => 'getIssuerReferenceId',
        'issuer_tin' => 'getIssuerTin',
        'tax_year' => 'getTaxYear',
        'federal_efile' => 'getFederalEfile',
        'federal_efile_status' => 'getFederalEfileStatus',
        'state_efile' => 'getStateEfile',
        'state_efile_status' => 'getStateEfileStatus',
        'postal_mail' => 'getPostalMail',
        'postal_mail_status' => 'getPostalMailStatus',
        'tin_match' => 'getTinMatch',
        'tin_match_status' => 'getTinMatchStatus',
        'address_verification' => 'getAddressVerification',
        'address_verification_status' => 'getAddressVerificationStatus',
        'reference_id' => 'getReferenceId',
        'email' => 'getEmail',
        'tin_type' => 'getTinType',
        'tin' => 'getTin',
        'recipient_name' => 'getRecipientName',
        'recipient_second_name' => 'getRecipientSecondName',
        'address' => 'getAddress',
        'address2' => 'getAddress2',
        'city' => 'getCity',
        'state' => 'getState',
        'zip' => 'getZip',
        'foreign_province' => 'getForeignProvince',
        'country_code' => 'getCountryCode',
        'validation_errors' => 'getValidationErrors',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'state_and_local_withholding' => 'getStateAndLocalWithholding'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['unique_form_id'] = $data['unique_form_id'] ?? null;
        $this->container['no_tin'] = $data['no_tin'] ?? null;
        $this->container['recipient_date_of_birth'] = $data['recipient_date_of_birth'] ?? null;
        $this->container['recipient_giin'] = $data['recipient_giin'] ?? null;
        $this->container['recipient_foreign_tin'] = $data['recipient_foreign_tin'] ?? null;
        $this->container['lob_code'] = $data['lob_code'] ?? null;
        $this->container['income_code'] = $data['income_code'] ?? null;
        $this->container['gross_income'] = $data['gross_income'] ?? null;
        $this->container['withholding_indicator'] = $data['withholding_indicator'] ?? null;
        $this->container['tax_country_code'] = $data['tax_country_code'] ?? null;
        $this->container['exemption_code_chap3'] = $data['exemption_code_chap3'] ?? null;
        $this->container['exemption_code_chap4'] = $data['exemption_code_chap4'] ?? null;
        $this->container['tax_rate_chap3'] = $data['tax_rate_chap3'] ?? null;
        $this->container['withholding_allowance'] = $data['withholding_allowance'] ?? null;
        $this->container['federal_tax_withheld'] = $data['federal_tax_withheld'] ?? null;
        $this->container['tax_not_deposited_indicator'] = $data['tax_not_deposited_indicator'] ?? null;
        $this->container['academic_indicator'] = $data['academic_indicator'] ?? null;
        $this->container['tax_withheld_other_agents'] = $data['tax_withheld_other_agents'] ?? null;
        $this->container['amount_repaid'] = $data['amount_repaid'] ?? null;
        $this->container['tax_paid_agent'] = $data['tax_paid_agent'] ?? null;
        $this->container['chap3_status_code'] = $data['chap3_status_code'] ?? null;
        $this->container['chap4_status_code'] = $data['chap4_status_code'] ?? null;
        $this->container['primary_withholding_agent'] = $data['primary_withholding_agent'] ?? null;
        $this->container['intermediary_or_flow_through'] = $data['intermediary_or_flow_through'] ?? null;
        $this->container['id'] = $data['id'] ?? null;
        $this->container['type'] = $data['type'] ?? null;
        $this->container['issuer_id'] = $data['issuer_id'] ?? null;
        $this->container['issuer_reference_id'] = $data['issuer_reference_id'] ?? null;
        $this->container['issuer_tin'] = $data['issuer_tin'] ?? null;
        $this->container['tax_year'] = $data['tax_year'] ?? null;
        $this->container['federal_efile'] = $data['federal_efile'] ?? null;
        $this->container['federal_efile_status'] = $data['federal_efile_status'] ?? null;
        $this->container['state_efile'] = $data['state_efile'] ?? null;
        $this->container['state_efile_status'] = $data['state_efile_status'] ?? null;
        $this->container['postal_mail'] = $data['postal_mail'] ?? null;
        $this->container['postal_mail_status'] = $data['postal_mail_status'] ?? null;
        $this->container['tin_match'] = $data['tin_match'] ?? null;
        $this->container['tin_match_status'] = $data['tin_match_status'] ?? null;
        $this->container['address_verification'] = $data['address_verification'] ?? null;
        $this->container['address_verification_status'] = $data['address_verification_status'] ?? null;
        $this->container['reference_id'] = $data['reference_id'] ?? null;
        $this->container['email'] = $data['email'] ?? null;
        $this->container['tin_type'] = $data['tin_type'] ?? null;
        $this->container['tin'] = $data['tin'] ?? null;
        $this->container['recipient_name'] = $data['recipient_name'] ?? null;
        $this->container['recipient_second_name'] = $data['recipient_second_name'] ?? null;
        $this->container['address'] = $data['address'] ?? null;
        $this->container['address2'] = $data['address2'] ?? null;
        $this->container['city'] = $data['city'] ?? null;
        $this->container['state'] = $data['state'] ?? null;
        $this->container['zip'] = $data['zip'] ?? null;
        $this->container['foreign_province'] = $data['foreign_province'] ?? null;
        $this->container['country_code'] = $data['country_code'] ?? null;
        $this->container['validation_errors'] = $data['validation_errors'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['updated_at'] = $data['updated_at'] ?? null;
        $this->container['state_and_local_withholding'] = $data['state_and_local_withholding'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ((mb_strlen($this->container['id']) < 1)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ((mb_strlen($this->container['type']) < 1)) {
            $invalidProperties[] = "invalid value for 'type', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['issuer_id'] === null) {
            $invalidProperties[] = "'issuer_id' can't be null";
        }
        if ($this->container['federal_efile'] === null) {
            $invalidProperties[] = "'federal_efile' can't be null";
        }
        if ($this->container['state_efile'] === null) {
            $invalidProperties[] = "'state_efile' can't be null";
        }
        if ($this->container['postal_mail'] === null) {
            $invalidProperties[] = "'postal_mail' can't be null";
        }
        if ($this->container['tin_match'] === null) {
            $invalidProperties[] = "'tin_match' can't be null";
        }
        if ($this->container['address_verification'] === null) {
            $invalidProperties[] = "'address_verification' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets unique_form_id
     *
     * @return string|null
     */
    public function getUniqueFormId()
    {
        return $this->container['unique_form_id'];
    }

    /**
     * Sets unique_form_id
     *
     * @param string|null $unique_form_id Unique form identifier
     *
     * @return self
     */
    public function setUniqueFormId($unique_form_id)
    {
        $this->container['unique_form_id'] = $unique_form_id;

        return $this;
    }

    /**
     * Gets no_tin
     *
     * @return bool|null
     */
    public function getNoTin()
    {
        return $this->container['no_tin'];
    }

    /**
     * Sets no_tin
     *
     * @param bool|null $no_tin No TIN indicator
     *
     * @return self
     */
    public function setNoTin($no_tin)
    {
        $this->container['no_tin'] = $no_tin;

        return $this;
    }

    /**
     * Gets recipient_date_of_birth
     *
     * @return \DateTime|null
     */
    public function getRecipientDateOfBirth()
    {
        return $this->container['recipient_date_of_birth'];
    }

    /**
     * Sets recipient_date_of_birth
     *
     * @param \DateTime|null $recipient_date_of_birth Recipient's date of birth
     *
     * @return self
     */
    public function setRecipientDateOfBirth($recipient_date_of_birth)
    {
        $this->container['recipient_date_of_birth'] = $recipient_date_of_birth;

        return $this;
    }

    /**
     * Gets recipient_giin
     *
     * @return string|null
     */
    public function getRecipientGiin()
    {
        return $this->container['recipient_giin'];
    }

    /**
     * Sets recipient_giin
     *
     * @param string|null $recipient_giin Recipient's GIIN (Global Intermediary Identification Number)
     *
     * @return self
     */
    public function setRecipientGiin($recipient_giin)
    {
        $this->container['recipient_giin'] = $recipient_giin;

        return $this;
    }

    /**
     * Gets recipient_foreign_tin
     *
     * @return string|null
     */
    public function getRecipientForeignTin()
    {
        return $this->container['recipient_foreign_tin'];
    }

    /**
     * Sets recipient_foreign_tin
     *
     * @param string|null $recipient_foreign_tin Recipient's foreign TIN
     *
     * @return self
     */
    public function setRecipientForeignTin($recipient_foreign_tin)
    {
        $this->container['recipient_foreign_tin'] = $recipient_foreign_tin;

        return $this;
    }

    /**
     * Gets lob_code
     *
     * @return string|null
     */
    public function getLobCode()
    {
        return $this->container['lob_code'];
    }

    /**
     * Sets lob_code
     *
     * @param string|null $lob_code Limitation on benefits code
     *
     * @return self
     */
    public function setLobCode($lob_code)
    {
        $this->container['lob_code'] = $lob_code;

        return $this;
    }

    /**
     * Gets income_code
     *
     * @return string|null
     */
    public function getIncomeCode()
    {
        return $this->container['income_code'];
    }

    /**
     * Sets income_code
     *
     * @param string|null $income_code Income code
     *
     * @return self
     */
    public function setIncomeCode($income_code)
    {
        $this->container['income_code'] = $income_code;

        return $this;
    }

    /**
     * Gets gross_income
     *
     * @return float|null
     */
    public function getGrossIncome()
    {
        return $this->container['gross_income'];
    }

    /**
     * Sets gross_income
     *
     * @param float|null $gross_income Gross income
     *
     * @return self
     */
    public function setGrossIncome($gross_income)
    {
        $this->container['gross_income'] = $gross_income;

        return $this;
    }

    /**
     * Gets withholding_indicator
     *
     * @return string|null
     */
    public function getWithholdingIndicator()
    {
        return $this->container['withholding_indicator'];
    }

    /**
     * Sets withholding_indicator
     *
     * @param string|null $withholding_indicator Withholding indicator
     *
     * @return self
     */
    public function setWithholdingIndicator($withholding_indicator)
    {
        $this->container['withholding_indicator'] = $withholding_indicator;

        return $this;
    }

    /**
     * Gets tax_country_code
     *
     * @return string|null
     */
    public function getTaxCountryCode()
    {
        return $this->container['tax_country_code'];
    }

    /**
     * Sets tax_country_code
     *
     * @param string|null $tax_country_code Country code
     *
     * @return self
     */
    public function setTaxCountryCode($tax_country_code)
    {
        $this->container['tax_country_code'] = $tax_country_code;

        return $this;
    }

    /**
     * Gets exemption_code_chap3
     *
     * @return string|null
     */
    public function getExemptionCodeChap3()
    {
        return $this->container['exemption_code_chap3'];
    }

    /**
     * Sets exemption_code_chap3
     *
     * @param string|null $exemption_code_chap3 Exemption code (Chapter 3)
     *
     * @return self
     */
    public function setExemptionCodeChap3($exemption_code_chap3)
    {
        $this->container['exemption_code_chap3'] = $exemption_code_chap3;

        return $this;
    }

    /**
     * Gets exemption_code_chap4
     *
     * @return string|null
     */
    public function getExemptionCodeChap4()
    {
        return $this->container['exemption_code_chap4'];
    }

    /**
     * Sets exemption_code_chap4
     *
     * @param string|null $exemption_code_chap4 Exemption code (Chapter 4)
     *
     * @return self
     */
    public function setExemptionCodeChap4($exemption_code_chap4)
    {
        $this->container['exemption_code_chap4'] = $exemption_code_chap4;

        return $this;
    }

    /**
     * Gets tax_rate_chap3
     *
     * @return string|null
     */
    public function getTaxRateChap3()
    {
        return $this->container['tax_rate_chap3'];
    }

    /**
     * Sets tax_rate_chap3
     *
     * @param string|null $tax_rate_chap3 Tax rate (Chapter 3)
     *
     * @return self
     */
    public function setTaxRateChap3($tax_rate_chap3)
    {
        $this->container['tax_rate_chap3'] = $tax_rate_chap3;

        return $this;
    }

    /**
     * Gets withholding_allowance
     *
     * @return float|null
     */
    public function getWithholdingAllowance()
    {
        return $this->container['withholding_allowance'];
    }

    /**
     * Sets withholding_allowance
     *
     * @param float|null $withholding_allowance Withholding allowance
     *
     * @return self
     */
    public function setWithholdingAllowance($withholding_allowance)
    {
        $this->container['withholding_allowance'] = $withholding_allowance;

        return $this;
    }

    /**
     * Gets federal_tax_withheld
     *
     * @return float|null
     */
    public function getFederalTaxWithheld()
    {
        return $this->container['federal_tax_withheld'];
    }

    /**
     * Sets federal_tax_withheld
     *
     * @param float|null $federal_tax_withheld Federal tax withheld
     *
     * @return self
     */
    public function setFederalTaxWithheld($federal_tax_withheld)
    {
        $this->container['federal_tax_withheld'] = $federal_tax_withheld;

        return $this;
    }

    /**
     * Gets tax_not_deposited_indicator
     *
     * @return bool|null
     */
    public function getTaxNotDepositedIndicator()
    {
        return $this->container['tax_not_deposited_indicator'];
    }

    /**
     * Sets tax_not_deposited_indicator
     *
     * @param bool|null $tax_not_deposited_indicator Tax not deposited indicator
     *
     * @return self
     */
    public function setTaxNotDepositedIndicator($tax_not_deposited_indicator)
    {
        $this->container['tax_not_deposited_indicator'] = $tax_not_deposited_indicator;

        return $this;
    }

    /**
     * Gets academic_indicator
     *
     * @return bool|null
     */
    public function getAcademicIndicator()
    {
        return $this->container['academic_indicator'];
    }

    /**
     * Sets academic_indicator
     *
     * @param bool|null $academic_indicator Academic indicator
     *
     * @return self
     */
    public function setAcademicIndicator($academic_indicator)
    {
        $this->container['academic_indicator'] = $academic_indicator;

        return $this;
    }

    /**
     * Gets tax_withheld_other_agents
     *
     * @return float|null
     */
    public function getTaxWithheldOtherAgents()
    {
        return $this->container['tax_withheld_other_agents'];
    }

    /**
     * Sets tax_withheld_other_agents
     *
     * @param float|null $tax_withheld_other_agents Tax withheld by other agents
     *
     * @return self
     */
    public function setTaxWithheldOtherAgents($tax_withheld_other_agents)
    {
        $this->container['tax_withheld_other_agents'] = $tax_withheld_other_agents;

        return $this;
    }

    /**
     * Gets amount_repaid
     *
     * @return float|null
     */
    public function getAmountRepaid()
    {
        return $this->container['amount_repaid'];
    }

    /**
     * Sets amount_repaid
     *
     * @param float|null $amount_repaid Amount repaid to recipient
     *
     * @return self
     */
    public function setAmountRepaid($amount_repaid)
    {
        $this->container['amount_repaid'] = $amount_repaid;

        return $this;
    }

    /**
     * Gets tax_paid_agent
     *
     * @return float|null
     */
    public function getTaxPaidAgent()
    {
        return $this->container['tax_paid_agent'];
    }

    /**
     * Sets tax_paid_agent
     *
     * @param float|null $tax_paid_agent Tax paid by withholding agent
     *
     * @return self
     */
    public function setTaxPaidAgent($tax_paid_agent)
    {
        $this->container['tax_paid_agent'] = $tax_paid_agent;

        return $this;
    }

    /**
     * Gets chap3_status_code
     *
     * @return string|null
     */
    public function getChap3StatusCode()
    {
        return $this->container['chap3_status_code'];
    }

    /**
     * Sets chap3_status_code
     *
     * @param string|null $chap3_status_code Chapter 3 status code
     *
     * @return self
     */
    public function setChap3StatusCode($chap3_status_code)
    {
        $this->container['chap3_status_code'] = $chap3_status_code;

        return $this;
    }

    /**
     * Gets chap4_status_code
     *
     * @return string|null
     */
    public function getChap4StatusCode()
    {
        return $this->container['chap4_status_code'];
    }

    /**
     * Sets chap4_status_code
     *
     * @param string|null $chap4_status_code Chapter 4 status code
     *
     * @return self
     */
    public function setChap4StatusCode($chap4_status_code)
    {
        $this->container['chap4_status_code'] = $chap4_status_code;

        return $this;
    }

    /**
     * Gets primary_withholding_agent
     *
     * @return \Avalara\SDK\Model\A1099\V2\PrimaryWithholdingAgentResponse|null
     */
    public function getPrimaryWithholdingAgent()
    {
        return $this->container['primary_withholding_agent'];
    }

    /**
     * Sets primary_withholding_agent
     *
     * @param \Avalara\SDK\Model\A1099\V2\PrimaryWithholdingAgentResponse|null $primary_withholding_agent Primary withholding agent information
     *
     * @return self
     */
    public function setPrimaryWithholdingAgent($primary_withholding_agent)
    {
        $this->container['primary_withholding_agent'] = $primary_withholding_agent;

        return $this;
    }

    /**
     * Gets intermediary_or_flow_through
     *
     * @return \Avalara\SDK\Model\A1099\V2\IntermediaryOrFlowThroughResponse|null
     */
    public function getIntermediaryOrFlowThrough()
    {
        return $this->container['intermediary_or_flow_through'];
    }

    /**
     * Sets intermediary_or_flow_through
     *
     * @param \Avalara\SDK\Model\A1099\V2\IntermediaryOrFlowThroughResponse|null $intermediary_or_flow_through Intermediary or flow-through entity information
     *
     * @return self
     */
    public function setIntermediaryOrFlowThrough($intermediary_or_flow_through)
    {
        $this->container['intermediary_or_flow_through'] = $intermediary_or_flow_through;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id ID of the form
     *
     * @return self
     */
    public function setId($id)
    {

        if ((mb_strlen($id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $id when calling Form1042SListItemResponse., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Type of the form. Will be one of:  * 940  * 941  * 943  * 944  * 945  * 1042  * 1042-S  * 1095-B  * 1095-C  * 1097-BTC  * 1098  * 1098-C  * 1098-E  * 1098-Q  * 1098-T  * 3921  * 3922  * 5498  * 5498-ESA  * 5498-SA  * 1099-MISC  * 1099-A  * 1099-B  * 1099-C  * 1099-CAP  * 1099-DIV  * 1099-G  * 1099-INT  * 1099-K  * 1099-LS  * 1099-LTC  * 1099-NEC  * 1099-OID  * 1099-PATR  * 1099-Q  * 1099-R  * 1099-S  * 1099-SA  * T4A  * W-2  * W-2G  * 1099-HC
     *
     * @return self
     */
    public function setType($type)
    {

        if ((mb_strlen($type) < 1)) {
            throw new \InvalidArgumentException('invalid length for $type when calling Form1042SListItemResponse., must be bigger than or equal to 1.');
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets issuer_id
     *
     * @return int
     */
    public function getIssuerId()
    {
        return $this->container['issuer_id'];
    }

    /**
     * Sets issuer_id
     *
     * @param int $issuer_id Issuer ID
     *
     * @return self
     */
    public function setIssuerId($issuer_id)
    {
        $this->container['issuer_id'] = $issuer_id;

        return $this;
    }

    /**
     * Gets issuer_reference_id
     *
     * @return string|null
     */
    public function getIssuerReferenceId()
    {
        return $this->container['issuer_reference_id'];
    }

    /**
     * Sets issuer_reference_id
     *
     * @param string|null $issuer_reference_id Issuer Reference ID
     *
     * @return self
     */
    public function setIssuerReferenceId($issuer_reference_id)
    {
        $this->container['issuer_reference_id'] = $issuer_reference_id;

        return $this;
    }

    /**
     * Gets issuer_tin
     *
     * @return string|null
     */
    public function getIssuerTin()
    {
        return $this->container['issuer_tin'];
    }

    /**
     * Sets issuer_tin
     *
     * @param string|null $issuer_tin Issuer TIN
     *
     * @return self
     */
    public function setIssuerTin($issuer_tin)
    {
        $this->container['issuer_tin'] = $issuer_tin;

        return $this;
    }

    /**
     * Gets tax_year
     *
     * @return int|null
     */
    public function getTaxYear()
    {
        return $this->container['tax_year'];
    }

    /**
     * Sets tax_year
     *
     * @param int|null $tax_year Tax year
     *
     * @return self
     */
    public function setTaxYear($tax_year)
    {
        $this->container['tax_year'] = $tax_year;

        return $this;
    }

    /**
     * Gets federal_efile
     *
     * @return bool
     */
    public function getFederalEfile()
    {
        return $this->container['federal_efile'];
    }

    /**
     * Sets federal_efile
     *
     * @param bool $federal_efile Boolean indicating that federal e-filing has been scheduled for this form
     *
     * @return self
     */
    public function setFederalEfile($federal_efile)
    {
        $this->container['federal_efile'] = $federal_efile;

        return $this;
    }

    /**
     * Gets federal_efile_status
     *
     * @return \Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse|null
     */
    public function getFederalEfileStatus()
    {
        return $this->container['federal_efile_status'];
    }

    /**
     * Sets federal_efile_status
     *
     * @param \Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse|null $federal_efile_status Federal e-file status
     *
     * @return self
     */
    public function setFederalEfileStatus($federal_efile_status)
    {
        $this->container['federal_efile_status'] = $federal_efile_status;

        return $this;
    }

    /**
     * Gets state_efile
     *
     * @return bool
     */
    public function getStateEfile()
    {
        return $this->container['state_efile'];
    }

    /**
     * Sets state_efile
     *
     * @param bool $state_efile Boolean indicating that state e-filing has been scheduled for this form
     *
     * @return self
     */
    public function setStateEfile($state_efile)
    {
        $this->container['state_efile'] = $state_efile;

        return $this;
    }

    /**
     * Gets state_efile_status
     *
     * @return \Avalara\SDK\Model\A1099\V2\StateEfileStatusDetailResponse[]|null
     */
    public function getStateEfileStatus()
    {
        return $this->container['state_efile_status'];
    }

    /**
     * Sets state_efile_status
     *
     * @param \Avalara\SDK\Model\A1099\V2\StateEfileStatusDetailResponse[]|null $state_efile_status State e-file status
     *
     * @return self
     */
    public function setStateEfileStatus($state_efile_status)
    {


        $this->container['state_efile_status'] = $state_efile_status;

        return $this;
    }

    /**
     * Gets postal_mail
     *
     * @return bool
     */
    public function getPostalMail()
    {
        return $this->container['postal_mail'];
    }

    /**
     * Sets postal_mail
     *
     * @param bool $postal_mail Boolean indicating that postal mailing to the recipient has been scheduled for this form
     *
     * @return self
     */
    public function setPostalMail($postal_mail)
    {
        $this->container['postal_mail'] = $postal_mail;

        return $this;
    }

    /**
     * Gets postal_mail_status
     *
     * @return \Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse|null
     */
    public function getPostalMailStatus()
    {
        return $this->container['postal_mail_status'];
    }

    /**
     * Sets postal_mail_status
     *
     * @param \Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse|null $postal_mail_status Postal mail to recipient status
     *
     * @return self
     */
    public function setPostalMailStatus($postal_mail_status)
    {
        $this->container['postal_mail_status'] = $postal_mail_status;

        return $this;
    }

    /**
     * Gets tin_match
     *
     * @return bool
     */
    public function getTinMatch()
    {
        return $this->container['tin_match'];
    }

    /**
     * Sets tin_match
     *
     * @param bool $tin_match Boolean indicating that TIN Matching has been scheduled for this form
     *
     * @return self
     */
    public function setTinMatch($tin_match)
    {
        $this->container['tin_match'] = $tin_match;

        return $this;
    }

    /**
     * Gets tin_match_status
     *
     * @return \Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse|null
     */
    public function getTinMatchStatus()
    {
        return $this->container['tin_match_status'];
    }

    /**
     * Sets tin_match_status
     *
     * @param \Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse|null $tin_match_status TIN Match status
     *
     * @return self
     */
    public function setTinMatchStatus($tin_match_status)
    {
        $this->container['tin_match_status'] = $tin_match_status;

        return $this;
    }

    /**
     * Gets address_verification
     *
     * @return bool
     */
    public function getAddressVerification()
    {
        return $this->container['address_verification'];
    }

    /**
     * Sets address_verification
     *
     * @param bool $address_verification Boolean indicating that address verification has been scheduled for this form
     *
     * @return self
     */
    public function setAddressVerification($address_verification)
    {
        $this->container['address_verification'] = $address_verification;

        return $this;
    }

    /**
     * Gets address_verification_status
     *
     * @return \Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse|null
     */
    public function getAddressVerificationStatus()
    {
        return $this->container['address_verification_status'];
    }

    /**
     * Sets address_verification_status
     *
     * @param \Avalara\SDK\Model\A1099\V2\Form1099StatusDetailResponse|null $address_verification_status Address verification status
     *
     * @return self
     */
    public function setAddressVerificationStatus($address_verification_status)
    {
        $this->container['address_verification_status'] = $address_verification_status;

        return $this;
    }

    /**
     * Gets reference_id
     *
     * @return string|null
     */
    public function getReferenceId()
    {
        return $this->container['reference_id'];
    }

    /**
     * Sets reference_id
     *
     * @param string|null $reference_id Reference ID
     *
     * @return self
     */
    public function setReferenceId($reference_id)
    {
        $this->container['reference_id'] = $reference_id;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Recipient email address
     *
     * @return self
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets tin_type
     *
     * @return string|null
     */
    public function getTinType()
    {
        return $this->container['tin_type'];
    }

    /**
     * Sets tin_type
     *
     * @param string|null $tin_type Type of TIN (Tax ID Number). Will be one of:  * SSN  * EIN  * ITIN  * ATIN
     *
     * @return self
     */
    public function setTinType($tin_type)
    {
        $this->container['tin_type'] = $tin_type;

        return $this;
    }

    /**
     * Gets tin
     *
     * @return string|null
     */
    public function getTin()
    {
        return $this->container['tin'];
    }

    /**
     * Sets tin
     *
     * @param string|null $tin Recipient Tax ID Number
     *
     * @return self
     */
    public function setTin($tin)
    {
        $this->container['tin'] = $tin;

        return $this;
    }

    /**
     * Gets recipient_name
     *
     * @return string|null
     */
    public function getRecipientName()
    {
        return $this->container['recipient_name'];
    }

    /**
     * Sets recipient_name
     *
     * @param string|null $recipient_name Recipient name
     *
     * @return self
     */
    public function setRecipientName($recipient_name)
    {
        $this->container['recipient_name'] = $recipient_name;

        return $this;
    }

    /**
     * Gets recipient_second_name
     *
     * @return string|null
     */
    public function getRecipientSecondName()
    {
        return $this->container['recipient_second_name'];
    }

    /**
     * Sets recipient_second_name
     *
     * @param string|null $recipient_second_name Recipient second name
     *
     * @return self
     */
    public function setRecipientSecondName($recipient_second_name)
    {
        $this->container['recipient_second_name'] = $recipient_second_name;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address Address
     *
     * @return self
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets address2
     *
     * @return string|null
     */
    public function getAddress2()
    {
        return $this->container['address2'];
    }

    /**
     * Sets address2
     *
     * @param string|null $address2 Address line 2
     *
     * @return self
     */
    public function setAddress2($address2)
    {
        $this->container['address2'] = $address2;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city City
     *
     * @return self
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state US state
     *
     * @return self
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets zip
     *
     * @return string|null
     */
    public function getZip()
    {
        return $this->container['zip'];
    }

    /**
     * Sets zip
     *
     * @param string|null $zip Zip/postal code
     *
     * @return self
     */
    public function setZip($zip)
    {
        $this->container['zip'] = $zip;

        return $this;
    }

    /**
     * Gets foreign_province
     *
     * @return string|null
     */
    public function getForeignProvince()
    {
        return $this->container['foreign_province'];
    }

    /**
     * Sets foreign_province
     *
     * @param string|null $foreign_province Foreign province
     *
     * @return self
     */
    public function setForeignProvince($foreign_province)
    {
        $this->container['foreign_province'] = $foreign_province;

        return $this;
    }

    /**
     * Gets country_code
     *
     * @return string|null
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string|null $country_code Country code, as defined at https://www.irs.gov/e-file-providers/country-codes
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets validation_errors
     *
     * @return \Avalara\SDK\Model\A1099\V2\ValidationErrorResponse[]|null
     */
    public function getValidationErrors()
    {
        return $this->container['validation_errors'];
    }

    /**
     * Sets validation_errors
     *
     * @param \Avalara\SDK\Model\A1099\V2\ValidationErrorResponse[]|null $validation_errors Validation errors
     *
     * @return self
     */
    public function setValidationErrors($validation_errors)
    {


        $this->container['validation_errors'] = $validation_errors;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at Creation time
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at Update time
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets state_and_local_withholding
     *
     * @return \Avalara\SDK\Model\A1099\V2\StateAndLocalWithholdingResponse|null
     */
    public function getStateAndLocalWithholding()
    {
        return $this->container['state_and_local_withholding'];
    }

    /**
     * Sets state_and_local_withholding
     *
     * @param \Avalara\SDK\Model\A1099\V2\StateAndLocalWithholdingResponse|null $state_and_local_withholding state_and_local_withholding
     *
     * @return self
     */
    public function setStateAndLocalWithholding($state_and_local_withholding)
    {
        $this->container['state_and_local_withholding'] = $state_and_local_withholding;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset):bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset):mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value):void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset):void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize():mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString():string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue():string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


